### ISSUE TITLE
String and object classes

### ISSUE THREAD

**Issue by angelawang24** [cshelman/4500a1p2#3]
Could you add all the methods/headers for the string and object class for consistency between all project? It can all be found on this piazza post: https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by cshelman** [comment]
We wont be able to change the repo until tomorrow, sorry. Also keep in mind we might not agree with all the issues created.

**Comment by cshelman** [comment]
We agree more with the object and string classes presented in [this](https://piazza.com/class/k51bluky59n2jr?cid=345) piazza post, we are changing the files to match them.
