### ISSUE TITLE
Inconsistent tests

### ISSUE THREAD

**Issue by angelawang24** [cshelman/4500a1p2#5]
For the test comparing a to b, a doesn't equal c based off the implementation for the function hash(). I'm basing my code off of the piazza post that has object class defined.
Object* a = new Object();
Object* b = new Object();
Object* c = new Object(a);
t_false(a->equals(b));
t_true(a->equals(c));

Solution: Remove or change t_true(a->equals(c)) test

**Comment by terryr1** [comment]
If this is the piazza post your refferring to: https://piazza.com/class/k51bluky59n2jr?cid=166

The comment for the hash functions states: 

 /** Returns the object's hash value. Two objects that are equal should         
   * have the same hash; object's that are not, may have the same hash.          
   * Subclasses should implement hash_me_(). */

In the case you disagree with Object c is copy of Object a and so both are equal. I'm not sure I understand why they should have different hashes

**Comment by cshelman** [comment]
Using the memory address as the hashcode of an object isn't really how a hashcode should be implemented if your code is modeled after that.

**Comment by cshelman** [comment]
Upon further thought, deleted t_false(a->equals(b)); test.
