### ISSUE TITLE
Instructor interface for object, helper, and string

### ISSUE THREAD

**Issue by noelprince** [cshelman/4500a1p2#6]
Hello, it would be helpful if you changed the interface for your string,  object, helper to match that of the instructors so everyone is on the same page. https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by cshelman** [comment]
We chose to use the standard classes from [this](https://piazza.com/class/k51bluky59n2jr?cid=345) piazza post as we agreed more with them than with the old utility ones.
